### ISSUE TITLE
ACL for allowing access to "localnet" should be configurable

### ISSUE THREAD

**Issue by wunzeco** [thias/puppet-squid3#20] opened 2015-01-19 18:14 UTC
The ACL rule below is a default configuration in squid.conf templates (short and long) and so gets applied always with this module

```
http_access allow localnet
```

However, this is not always desirable. For instance, assuming you want to restrict outbound internet access of your private network to a few whitelisted sites. In this case the desired ACL in squid.conf should look like below to achieve the expected access restriction. 

```
<...snip...>
# user-defined ACLs
acl sitesWhitelist dstdomain "/etc/squid3/sites.whitelist"

# user-defined http_accesses
http_access allow localnet sitesWhitelist
http_access allow localhost
http_access deny all

<...snip...>
```

**Comment by thias** [comment] 2015-11-16 11:04
This partially overlaps with changes proposed in #24. I'll try to think of something, otherwise a clean PR of the shared change would be great!

**Comment by thias** [comment] 2015-11-16 11:06
Actually, this is a duplicate of #17.

**Closed by thias** 2015-11-16 11:06 UTC
